source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

gem 'compass-rails'
gem 'i18n'
gem 'rails-i18n'
gem 'sprockets-cjs',         '~> 0.2.1'
gem 'htmlcompressor',        '~> 0.1.2'
gem 'attribute_normalizer',  '~> 1.2.0'
gem 'fog',                   '~> 1.20'
gem 'asset_sync'
gem 'resque', require: 'resque/server'
gem 'resque_mailer'
gem 'capistrano-resque', '~> 0.2.1', require: false
gem 'validates_email_format_of'
gem 'newrelic_rpm'
gem 'health_check'
gem 'simple_form'

group :development do
  gem 'capistrano',            '~> 3.2.1'
  gem 'capistrano-bundler',    '~> 1.1.3'
  gem 'capistrano-rails',      '~> 1.1.2'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'quiet_assets'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
