source 'https://rubygems.org'

gem 'rails', '4.1.6'
gem 'sass-rails', '~> 5.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'compass-rails'
gem 'i18n'
gem 'rails-i18n'
gem 'sprockets-cjs',         '~> 0.2.1'
gem 'htmlcompressor',        '~> 0.1.2'
gem 'attribute_normalizer',  '~> 1.2.0'
gem 'fog',                   '~> 1.20'
gem 'asset_sync'
gem 'resque', require: 'resque/server'
gem 'resque_mailer'
gem 'capistrano-resque', '~> 0.2.1', require: false
gem 'validates_email_format_of'
gem 'newrelic_rpm'
gem 'health_check'
gem 'simple_form'

group :production, :staging do
  gem 'mysql2'
end

group :development do
  gem 'sqlite3'
  gem 'capistrano',            '~> 3.2.1'
  gem 'capistrano-bundler',    '~> 1.1.3'
  gem 'capistrano-rails',      '~> 1.1.2'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'quiet_assets'
  gem 'spring'
end
